"use client";

/**
 * Ícones que a Gestão (módulos) e cada usuário (atalhos) podem escolher.
 * O banco guarda só o NOME (ex.: "chart-bar"); aqui o nome vira o ícone Tabler.
 * Para oferecer um ícone novo, acrescente uma linha na lista abaixo.
 */
import {
    IconArchive,
    IconAward,
    IconBell,
    IconBook,
    IconBookmark,
    IconBox,
    IconBrain,
    IconBriefcase,
    IconBuilding,
    IconBuildingChurch,
    IconBuildingStore,
    IconBulb,
    IconCalendar,
    IconCalendarEvent,
    IconCamera,
    IconCar,
    IconCash,
    IconChartBar,
    IconChartPie,
    IconChecklist,
    IconClipboardCheck,
    IconClipboardList,
    IconClipboardPlus,
    IconClock,
    IconCoin,
    IconCross,
    IconCurrencyDollar,
    IconDatabase,
    IconDeviceDesktopAnalytics,
    IconEye,
    IconFileInvoice,
    IconFileText,
    IconFlag,
    IconFlower,
    IconFolder,
    IconGift,
    IconHeadset,
    IconHeart,
    IconHeartHandshake,
    IconHistory,
    IconHome,
    IconId,
    IconLayoutDashboard,
    IconLayoutSidebar,
    IconListDetails,
    IconLock,
    IconMail,
    IconMapPin,
    IconMessageCircle,
    IconMessages,
    IconNews,
    IconPackage,
    IconPhone,
    IconPrinter,
    IconReceipt,
    IconReportAnalytics,
    IconSearch,
    IconSettings,
    IconShieldLock,
    IconSparkles,
    IconSpeakerphone,
    IconStar,
    IconStethoscope,
    IconTool,
    IconTruck,
    IconTruckDelivery,
    IconUserCheck,
    IconUserCog,
    IconUserPlus,
    IconUsers,
    IconUsersGroup,
    IconWallet,
} from "@tabler/icons-react";
import type React from "react";

export type IconeTabler = React.ElementType<any>;

/** nome → ícone. A ordem é a da grade de escolha. */
export const ICONES: Record<string, IconeTabler> = {
    home: IconHome,
    "device-desktop-analytics": IconDeviceDesktopAnalytics,
    "layout-dashboard": IconLayoutDashboard,
    "file-invoice": IconFileInvoice,
    "file-text": IconFileText,
    "clipboard-list": IconClipboardList,
    "clipboard-check": IconClipboardCheck,
    "clipboard-plus": IconClipboardPlus,
    checklist: IconChecklist,
    messages: IconMessages,
    "message-circle": IconMessageCircle,
    sparkles: IconSparkles,
    speakerphone: IconSpeakerphone,
    bell: IconBell,
    mail: IconMail,
    phone: IconPhone,
    headset: IconHeadset,
    "heart-handshake": IconHeartHandshake,
    heart: IconHeart,
    flower: IconFlower,
    cross: IconCross,
    "building-church": IconBuildingChurch,
    eye: IconEye,
    package: IconPackage,
    box: IconBox,
    archive: IconArchive,
    search: IconSearch,
    "building-store": IconBuildingStore,
    "truck-delivery": IconTruckDelivery,
    truck: IconTruck,
    car: IconCar,
    "map-pin": IconMapPin,
    book: IconBook,
    bookmark: IconBookmark,
    "currency-dollar": IconCurrencyDollar,
    coin: IconCoin,
    cash: IconCash,
    wallet: IconWallet,
    receipt: IconReceipt,
    "chart-bar": IconChartBar,
    "chart-pie": IconChartPie,
    "report-analytics": IconReportAnalytics,
    "list-details": IconListDetails,
    "shield-lock": IconShieldLock,
    lock: IconLock,
    users: IconUsers,
    "users-group": IconUsersGroup,
    "user-plus": IconUserPlus,
    "user-check": IconUserCheck,
    "user-cog": IconUserCog,
    id: IconId,
    stethoscope: IconStethoscope,
    gift: IconGift,
    star: IconStar,
    award: IconAward,
    news: IconNews,
    calendar: IconCalendar,
    "calendar-event": IconCalendarEvent,
    clock: IconClock,
    history: IconHistory,
    brain: IconBrain,
    bulb: IconBulb,
    database: IconDatabase,
    settings: IconSettings,
    tool: IconTool,
    "layout-sidebar": IconLayoutSidebar,
    briefcase: IconBriefcase,
    building: IconBuilding,
    folder: IconFolder,
    flag: IconFlag,
    camera: IconCamera,
    printer: IconPrinter,
};

export const NOMES_ICONES = Object.keys(ICONES);

/** Ícone pelo nome (ou undefined se o nome não existe). */
export function iconePorNome(nome?: string | null): IconeTabler | undefined {
    return nome ? ICONES[nome] : undefined;
}

/** Nome de um ícone (o contrário de iconePorNome). Ícone fora da lista → "". */
export function nomeDoIcone(icone: unknown): string {
    for (const [nome, comp] of Object.entries(ICONES)) if (comp === icone) return nome;
    return "";
}
